# Generated by Django 3.2.9 on 2022-07-16 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty_Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brief', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('name2', models.CharField(blank=True, max_length=100)),
                ('price2', models.CharField(blank=True, max_length=100)),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brief2', models.CharField(blank=True, max_length=100)),
                ('description2', models.TextField(blank=True)),
                ('name3', models.CharField(blank=True, max_length=100)),
                ('price3', models.CharField(blank=True, max_length=100)),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brief3', models.CharField(blank=True, max_length=100)),
                ('description3', models.TextField(blank=True)),
                ('name4', models.CharField(blank=True, max_length=100)),
                ('price4', models.CharField(blank=True, max_length=100)),
                ('image4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brief4', models.CharField(blank=True, max_length=100)),
                ('description4', models.TextField(blank=True)),
                ('postingDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
