# Generated by Django 3.2.9 on 2022-06-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brief', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('postingDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
